name: incas-srl
channels:
   - conda-forge
   - defaults
dependencies:
   - python=3.7.2
   - flask
   - flask-cors
   - tornado
   - requests
   - cython
   - pip
   - pip:
       - transformer-srl==2.4.6
       - clean-text
       - pandas
       - nltk
       - allennlp
       - allennlp-models
       - spacy
       - torch


